name: NormativeNeuroDev_CrossSec_T1
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.2=h0a44026_0
  - openssl=1.1.1d=h1de35cc_4
  - pip=20.0.2=py37_1
  - python=3.7.6=h359304d_2
  - readline=7.0=h1de35cc_5
  - setuptools=45.2.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appnope==0.1.0
    - apptools==4.5.0
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.1
    - chardet==3.0.4
    - configobj==5.0.6
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - envisage==4.9.2
    - glob3==0.0.1
    - idna==2.9
    - importlib-metadata==1.5.0
    - ipykernel==5.1.4
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - jinja2==2.11.1
    - joblib==0.14.1
    - json5==0.9.2
    - jsonschema==3.2.0
    - jupyter-client==6.0.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-core==4.6.3
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab==2.0.0
    - jupyterlab-server==1.0.7
    - kiwisolver==1.1.0
    - littleutils==0.2.2
    - lxml==4.5.0
    - markupsafe==1.1.1
    - matplotlib==3.1.3
    - mayavi==4.7.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - nibabel==3.0.1
    - notebook==6.0.3
    - numpy==1.18.1
    - outdated==0.2.0
    - pandas==1.0.1
    - pandas-flavor==0.2.0
    - pandocfilters==1.4.2
    - parso==0.6.2
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pingouin==0.3.3
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.3
    - ptyprocess==0.6.0
    - pyface==6.1.2
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyqt5==5.14.1
    - pyqt5-sip==12.7.1
    - pyrsistent==0.15.7
    - pysurfer==0.10.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyyaml==5.3
    - pyzmq==19.0.0
    - requests==2.23.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - seaborn==0.10.0
    - send2trash==1.5.0
    - six==1.14.0
    - sklearn==0.0
    - statsmodels==0.11.1
    - terminado==0.8.3
    - testpath==0.4.4
    - torch==1.4.0
    - tornado==6.0.4
    - traitlets==4.3.3
    - traits==6.0.0
    - traitsui==6.1.3
    - urllib3==1.25.8
    - vtk==8.1.2
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - xarray==0.15.0
    - zipp==3.1.0
prefix: /Users/lindenmp/opt/anaconda3/envs/NormativeNeuroDev_CrossSec_T1

